import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import tailwind from "bun-plugin-tailwind";
import { join, relative } from "node:path";
import { randomUUID } from "node:crypto";
import { InvalidInput } from "../../src/domain/errors";
export const buildUi = Effect.fn("Build.ui")(function*(root: string) {
  const fs = yield* FileSystem.FileSystem;
  const dist = join(root, "dist");
  const generated = join(root, "src/generated");
  yield* fs.makeDirectory(dist, { recursive: true });
  yield* fs.makeDirectory(generated, { recursive: true });
  const candidate = yield* Effect.acquireRelease(fs.makeTempDirectory({ directory: dist, prefix: ".candidate-" }), path => fs.remove(path, { recursive: true, force: true }).pipe(Effect.catch(error => Effect.logWarning("Build candidate cleanup failed", error.message))));
  const build = (options: Parameters<typeof Bun.build>[0]) => Effect.tryPromise({ try: () => Bun.build(options), catch: cause => new InvalidInput({ message: String(cause) }) }).pipe(Effect.flatMap(output => output.success ? Effect.succeed(output) : Effect.fail(new InvalidInput({ message: output.logs.map(log => log.message).join("\n") }))));
  yield* Effect.all([
    build({ entrypoints: [join(root, "src/ui/index.html")], outdir: join(candidate, "ui"), plugins: [tailwind], minify: true, target: "browser", define: { "process.env.NODE_ENV": JSON.stringify("production") }, throw: false }),
    build({ entrypoints: [join(root, "src/runtime/runtime.ts")], outdir: candidate, naming: "runtime.js", format: "iife", minify: true, target: "browser", throw: false }),
  ], { concurrency: 2 });
  const published = join(dist, "builds", randomUUID());
  yield* fs.makeDirectory(join(dist, "builds"), { recursive: true });
  yield* fs.rename(candidate, published);
  const imports: string[] = [];
  const entry = (file: string) => {
    const name = `f${imports.length}`;
    imports.push(`import ${name} from ${JSON.stringify(relative(generated, file))} with { type: "file" };`);
    return name;
  };
  const group = Effect.fnUntraced(function*(dir: string) {
    const files = yield* Effect.tryPromise(() => Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: dir, dot: true })));
    return `{\n${files.sort().map(file => `  ${JSON.stringify(file)}: ${entry(join(dir, file))},`).join("\n")}\n}`;
  });
  const ui = yield* group(join(published, "ui"));
  const scaffold = yield* group(join(root, "src/scaffold"));
  const runtime = entry(join(published, "runtime.js"));
  const manifest = `// Generated by scripts/build-ui.ts. Do not edit.\n${imports.join("\n")}\n\nexport const uiFiles = ${ui};\n\nexport const scaffoldFiles = ${scaffold};\n\nexport const runtimeFile = ${runtime};\n`;
  // Existing server processes retain immutable files; only the manifest advances.
  const temporary = join(generated, `assets-${randomUUID()}.tmp`);
  yield* Effect.scoped(Effect.gen(function*() {
    yield* Effect.addFinalizer(() => fs.remove(temporary, { force: true }).pipe(Effect.catch(error => Effect.logWarning("Manifest cleanup failed", error.message))));
    yield* fs.writeFileString(temporary, manifest);
    yield* fs.rename(temporary, join(generated, "assets.js"));
  }));
  yield* fs.writeFileString(join(generated, "assets.d.ts"), `// Generated by scripts/build-ui.ts. Do not edit.\nexport declare const uiFiles: Record<string, string>;\nexport declare const scaffoldFiles: Record<string, string>;\nexport declare const runtimeFile: string;\n`);
  yield* Effect.logInfo(`built ui + runtime: ${published}`);
  return published;
});
