import { gzipSync } from "node:zlib";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import tailwind from "bun-plugin-tailwind";
import { join, relative } from "node:path";
import { randomUUID } from "node:crypto";
import { InvalidInput } from "../../src/domain/errors";
export const buildUi = Effect.fn("Build.ui")(function* (root: string) {
  const fs = yield* FileSystem.FileSystem;
  const dist = join(root, "dist");
  const generated = join(root, "src/generated");
  yield* fs.makeDirectory(dist, { recursive: true });
  yield* fs.makeDirectory(generated, { recursive: true });
  const candidate = yield* Effect.acquireRelease(
    fs.makeTempDirectory({ directory: dist, prefix: ".candidate-" }),
    (path) =>
      fs
        .remove(path, { recursive: true, force: true })
        .pipe(
          Effect.catch((error) =>
            Effect.logWarning("Build candidate cleanup failed", error.message),
          ),
        ),
  );
  const build = (options: Parameters<typeof Bun.build>[0]) =>
    Effect.tryPromise({
      try: () => Bun.build(options),
      catch: (cause) => new InvalidInput({ message: String(cause) }),
    }).pipe(
      Effect.flatMap((output) =>
        output.success
          ? Effect.succeed(output)
          : Effect.fail(
              new InvalidInput({
                message: output.logs.map((log) => log.message).join("\n"),
              }),
            ),
      ),
    );
  yield* Effect.all(
    [
      build({
        entrypoints: [join(root, "src/ui/index.html")],
        outdir: join(candidate, "ui"),
        plugins: [tailwind],
        minify: true,
        target: "browser",
        define: { "process.env.NODE_ENV": JSON.stringify("production") },
        throw: false,
      }),
      build({
        entrypoints: [join(root, "src/runtime/runtime.ts")],
        outdir: candidate,
        naming: "runtime.js",
        format: "iife",
        minify: true,
        target: "browser",
        throw: false,
      }),
    ],
    { concurrency: 2 },
  );
  // Tailwind's Bun plugin inlines fonts. Keep them independently cacheable.
  const uiDirectory = join(candidate, "ui");
  for (const name of yield* fs.readDirectory(uiDirectory)) {
    if (!name.endsWith(".css")) continue;
    const original = yield* fs.readFileString(join(uiDirectory, name));
    const fonts = new Map<string, Uint8Array>();
    const css = original.replace(
      /data:font\/woff2;base64,([A-Za-z0-9+/=]+)/g,
      (_, encoded: string) => {
        const bytes = Buffer.from(encoded, "base64");
        const name = `font-${Bun.hash(bytes).toString(16)}.woff2`;
        fonts.set(name, bytes);
        return `./${name}`;
      },
    );
    if (css === original) continue;
    for (const [font, bytes] of fonts)
      yield* fs.writeFile(join(uiDirectory, font), bytes);
    const renamed = `styles-${Bun.hash(css).toString(16)}.css`;
    yield* fs.writeFileString(join(uiDirectory, renamed), css);
    yield* fs.remove(join(uiDirectory, name));
    const html = yield* fs.readFileString(join(uiDirectory, "index.html"));
    yield* fs.writeFileString(
      join(uiDirectory, "index.html"),
      html.replaceAll(name, renamed),
    );
  }
  const fontLicense = join(root, "src/ui/fonts/LICENSE.txt");
  if (yield* fs.exists(fontLicense))
    yield* fs.writeFileString(
      join(uiDirectory, "font-license.txt"),
      yield* fs.readFileString(fontLicense),
    );
  const imports: string[] = [];
  const entry = (file: string) => {
    const name = `f${imports.length}`;
    imports.push(
      `import ${name} from ${JSON.stringify(relative(generated, file).replaceAll("\\", "/"))} with { type: "file" };`,
    );
    return name;
  };
  const group = Effect.fnUntraced(function* (
    dir: string,
    embedded: boolean,
    compressed = false,
  ) {
    const files = yield* Effect.tryPromise(() =>
      Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: dir, dot: true })),
    );
    const entries = yield* Effect.forEach(files.sort(), (file) =>
      Effect.gen(function* () {
        const value = embedded
          ? `bytes(${JSON.stringify(Buffer.from(compressed ? gzipSync(yield* fs.readFile(join(dir, file))) : yield* fs.readFile(join(dir, file))).toString("base64"))})`
          : entry(join(dir, file));
        return `  ${JSON.stringify(file.replaceAll("\\", "/"))}: ${value},`;
      }),
    );
    return `{\n${entries.join("\n")}\n}`;
  });
  const ui = yield* group(join(candidate, "ui"), true);
  const uiGzip = yield* group(join(candidate, "ui"), true, true);
  const scaffold = yield* group(join(root, "src/scaffold"), false);
  const runtime = `bytes(${JSON.stringify(Buffer.from(yield* fs.readFile(join(candidate, "runtime.js"))).toString("base64"))})`;
  const runtimeGzip = `bytes(${JSON.stringify(gzipSync(yield* fs.readFile(join(candidate, "runtime.js"))).toString("base64"))})`;
  const manifest = `// Generated by scripts/build-ui.ts. Do not edit.\n${imports.join("\n")}\n\nconst bytes = (value) => Buffer.from(value, "base64");\n\nexport const uiFiles = ${ui};\nexport const uiGzipFiles = ${uiGzip};\n\nexport const scaffoldFiles = ${scaffold};\n\nexport const runtimeFile = ${runtime};\nexport const runtimeGzipFile = ${runtimeGzip};\n`;
  // Loaded manifests own immutable bytes; no server retains candidate file paths.
  const temporary = join(generated, `assets-${randomUUID()}.tmp`);
  yield* Effect.scoped(
    Effect.gen(function* () {
      yield* Effect.addFinalizer(() =>
        fs
          .remove(temporary, { force: true })
          .pipe(
            Effect.catch((error) =>
              Effect.logWarning("Manifest cleanup failed", error.message),
            ),
          ),
      );
      yield* fs.writeFileString(temporary, manifest);
      yield* fs.rename(temporary, join(generated, "assets.js"));
    }),
  );
  yield* fs.writeFileString(
    join(generated, "assets.d.ts"),
    `// Generated by scripts/build-ui.ts. Do not edit.\nexport declare const uiFiles: Record<string, Uint8Array>;\nexport declare const uiGzipFiles: Record<string, Uint8Array>;\nexport declare const scaffoldFiles: Record<string, string>;\nexport declare const runtimeFile: Uint8Array;\nexport declare const runtimeGzipFile: Uint8Array;\n`,
  );
  yield* Effect.logInfo("built ui + runtime: immutable asset manifest");
});
