import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import tailwind from "bun-plugin-tailwind";
import { join, relative } from "node:path";
import { randomUUID } from "node:crypto";
import { InvalidInput } from "../../src/domain/errors";
export const buildUi = Effect.fn("Build.ui")(function* (root: string) {
  const fs = yield* FileSystem.FileSystem;
  const dist = join(root, "dist");
  const generated = join(root, "src/generated");
  yield* fs.makeDirectory(dist, { recursive: true });
  yield* fs.makeDirectory(generated, { recursive: true });
  const candidate = yield* Effect.acquireRelease(
    fs.makeTempDirectory({ directory: dist, prefix: ".candidate-" }),
    (path) =>
      fs
        .remove(path, { recursive: true, force: true })
        .pipe(
          Effect.catch((error) =>
            Effect.logWarning("Build candidate cleanup failed", error.message),
          ),
        ),
  );
  const build = (options: Parameters<typeof Bun.build>[0]) =>
    Effect.tryPromise({
      try: () => Bun.build(options),
      catch: (cause) => new InvalidInput({ message: String(cause) }),
    }).pipe(
      Effect.flatMap((output) =>
        output.success
          ? Effect.succeed(output)
          : Effect.fail(
              new InvalidInput({
                message: output.logs.map((log) => log.message).join("\n"),
              }),
            ),
      ),
    );
  yield* Effect.all(
    [
      build({
        entrypoints: [join(root, "src/ui/index.html")],
        outdir: join(candidate, "ui"),
        plugins: [tailwind],
        minify: true,
        target: "browser",
        define: { "process.env.NODE_ENV": JSON.stringify("production") },
        throw: false,
      }),
      build({
        entrypoints: [join(root, "src/runtime/runtime.ts")],
        outdir: candidate,
        naming: "runtime.js",
        format: "iife",
        minify: true,
        target: "browser",
        throw: false,
      }),
    ],
    { concurrency: 2 },
  );
  const imports: string[] = [];
  const entry = (file: string) => {
    const name = `f${imports.length}`;
    imports.push(
      `import ${name} from ${JSON.stringify(relative(generated, file))} with { type: "file" };`,
    );
    return name;
  };
  const group = Effect.fnUntraced(function* (dir: string, embedded: boolean) {
    const files = yield* Effect.tryPromise(() =>
      Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: dir, dot: true })),
    );
    const entries = yield* Effect.forEach(files.sort(), (file) =>
      Effect.gen(function* () {
        const value = embedded
          ? `bytes(${JSON.stringify(Buffer.from(yield* fs.readFile(join(dir, file))).toString("base64"))})`
          : entry(join(dir, file));
        return `  ${JSON.stringify(file)}: ${value},`;
      }),
    );
    return `{\n${entries.join("\n")}\n}`;
  });
  const ui = yield* group(join(candidate, "ui"), true);
  const scaffold = yield* group(join(root, "src/scaffold"), false);
  const runtime = `bytes(${JSON.stringify(Buffer.from(yield* fs.readFile(join(candidate, "runtime.js"))).toString("base64"))})`;
  const manifest = `// Generated by scripts/build-ui.ts. Do not edit.\n${imports.join("\n")}\n\nconst bytes = (value) => Buffer.from(value, "base64");\n\nexport const uiFiles = ${ui};\n\nexport const scaffoldFiles = ${scaffold};\n\nexport const runtimeFile = ${runtime};\n`;
  // Loaded manifests own immutable bytes; no server retains candidate file paths.
  const temporary = join(generated, `assets-${randomUUID()}.tmp`);
  yield* Effect.scoped(
    Effect.gen(function* () {
      yield* Effect.addFinalizer(() =>
        fs
          .remove(temporary, { force: true })
          .pipe(
            Effect.catch((error) =>
              Effect.logWarning("Manifest cleanup failed", error.message),
            ),
          ),
      );
      yield* fs.writeFileString(temporary, manifest);
      yield* fs.rename(temporary, join(generated, "assets.js"));
    }),
  );
  yield* fs.writeFileString(
    join(generated, "assets.d.ts"),
    `// Generated by scripts/build-ui.ts. Do not edit.\nexport declare const uiFiles: Record<string, Uint8Array>;\nexport declare const scaffoldFiles: Record<string, string>;\nexport declare const runtimeFile: Uint8Array;\n`,
  );
  yield* Effect.logInfo("built ui + runtime: immutable asset manifest");
});
