/**
 * Builds the canvas UI and the in-frame runtime into dist/, then generates src/generated/assets.js:
 * a manifest that imports every file framio ships (UI, runtime, .framio scaffold) with
 * `type: "file"`. From source those resolve to paths on disk; in the compiled binary they are
 * embedded. Pass --watch to rebuild on change.
 */
import tailwind from "bun-plugin-tailwind";
import { mkdirSync, rmSync, watch, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const root = join(import.meta.dir, "..");
const dist = join(root, "dist");
const generated = join(root, "src/generated");

async function build() {
  const t = performance.now();
  rmSync(join(dist, "ui"), { recursive: true, force: true });
  const [ui, runtime] = await Promise.all([
    Bun.build({
      entrypoints: [join(root, "src/ui/index.html")],
      outdir: join(dist, "ui"),
      plugins: [tailwind],
      minify: true,
      target: "browser",
      define: { "process.env.NODE_ENV": JSON.stringify("production") },
      throw: false,
    }),
    Bun.build({
      entrypoints: [join(root, "src/runtime/runtime.ts")],
      outdir: dist,
      naming: "runtime.js",
      format: "iife",
      minify: true,
      target: "browser",
      throw: false,
    }),
  ]);
  for (const out of [ui, runtime]) if (!out.success) for (const l of out.logs) console.error(l);
  await generateAssets();
  console.log(`built ui + runtime in ${Math.round(performance.now() - t)}ms`);
}

async function listFiles(dir: string) {
  const files = await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: dir, dot: true }));
  return files.sort();
}

async function generateAssets() {
  mkdirSync(generated, { recursive: true });
  const imports: string[] = [];
  const entry = (abs: string) => {
    const name = `f${imports.length}`;
    imports.push(`import ${name} from ${JSON.stringify(relative(generated, abs))} with { type: "file" };`);
    return name;
  };
  const group = async (dir: string) =>
    `{\n${(await listFiles(dir)).map((f) => `  ${JSON.stringify(f)}: ${entry(join(dir, f))},`).join("\n")}\n}`;

  const ui = await group(join(dist, "ui"));
  const scaffold = await group(join(root, "src/scaffold"));
  const runtime = entry(join(dist, "runtime.js"));
  writeFileSync(
    join(generated, "assets.js"),
    `// Generated by scripts/build-ui.ts. Do not edit.\n${imports.join("\n")}\n\n` +
      `export const uiFiles = ${ui};\n\nexport const scaffoldFiles = ${scaffold};\n\nexport const runtimeFile = ${runtime};\n`,
  );
  writeFileSync(
    join(generated, "assets.d.ts"),
    `// Generated by scripts/build-ui.ts. Do not edit.\n` +
      `/** Relative path -> readable file path (on disk from source, embedded in the binary). */\n` +
      `export declare const uiFiles: Record<string, string>;\n` +
      `export declare const scaffoldFiles: Record<string, string>;\n` +
      `export declare const runtimeFile: string;\n`,
  );
}

await build();

if (process.argv.includes("--watch")) {
  let timer: Timer | null = null;
  for (const dir of ["src/ui", "src/runtime", "src/scaffold"]) {
    watch(join(root, dir), { recursive: true }, () => {
      if (timer) clearTimeout(timer);
      timer = setTimeout(build, 80);
    });
  }
  console.log("watching src/ui, src/runtime, src/scaffold");
}
